nodes:
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.AnemoiDatasetNodes
      dataset:
        cutout:
          - dataset: /mnt/weatherloss/WindPower/data/WindAI/Anemoidatasets/New_Cerra_A_large.zarr
          - dataset: /mnt/weatherloss/WindPower/data/WindAI/Anemoidatasets/era5_A_large.zarr
        min_distance_km: 0
        adjust: all
    attributes:
      area_weight:
        _target_: anemoi.graphs.nodes.attributes.UniformWeights
        norm: unit-max
      cutout:
        _target_: anemoi.graphs.nodes.attributes.CutOutMask
      boundary:
        _target_: anemoi.graphs.nodes.attributes.BooleanNot
        masks:
          _target_: anemoi.graphs.nodes.attributes.CutOutMask
      # turbine_mask:
      #   _target_: anemoi.graphs.nodes.attributes.masks.NonmissingAnemoiDatasetVariable
      #   variable: turbinemask

  hidden:
    node_builder:
      _target_: anemoi.graphs.nodes.LimitedAreaTriNodes
      resolution: 9
      reference_node_name: data
      mask_attr_name: cutout
      margin_radius_km: 300

edges:
  - source_name: data
    target_name: hidden
    edge_builders:
      - _target_: anemoi.graphs.edges.KNNEdges
        num_nearest_neighbours: 12
        source_mask_attr_name: cutout
      - _target_: anemoi.graphs.edges.CutOffEdges
        cutoff_distance_km: 15
        source_mask_attr_name: boundary
    attributes:
      edge_length:
        _target_: anemoi.graphs.edges.attributes.EdgeLength
        norm: unit-max
      edge_dirs:
        _target_: anemoi.graphs.edges.attributes.EdgeDirection
        norm: unit-std

  - source_name: hidden
    target_name: hidden
    edge_builders:
      - _target_: anemoi.graphs.edges.MultiScaleEdges
        x_hops: 1
        scale_resolutions: 9
    attributes:
      edge_length:
        _target_: anemoi.graphs.edges.attributes.EdgeLength
        norm: unit-max
      edge_dirs:
        _target_: anemoi.graphs.edges.attributes.EdgeDirection
        norm: unit-std

  - source_name: hidden
    target_name: data
    edge_builders:
      - _target_: anemoi.graphs.edges.KNNEdges
        target_mask_attr_name: cutout
        num_nearest_neighbours: 3
    attributes:
      edge_length:
        _target_: anemoi.graphs.edges.attributes.EdgeLength
        norm: unit-max
      edge_dirs:
        _target_: anemoi.graphs.edges.attributes.EdgeDirection
        norm: unit-std

post_processors:
  - _target_: anemoi.graphs.processors.RestrictEdgeLength
    source_name: data
    target_name: hidden
    max_length_km: 20
    source_mask_attr_name: cutout

  - _target_: anemoi.graphs.processors.RemoveUnconnectedNodes
    nodes_name: data
    ignore: cutout
    save_mask_indices_to_attr: indices_connected_nodes